export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const TYPING = 'TYPING';
export const CLEAR_TYPING = 'CLEAR_TYPING';
export const ADD_BOOK_QUERY = 'ADD_BOOK_QUERY';
export const INVALID_SOURCE = 'INVALID_SOURCE';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_NEW_BOOK_SUCCESS = 'GET_NEW_BOOK_SUCCESS';
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
export const GET_NEXT_BOOK = 'GET_NEXT_BOOK';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const POST_BOOK_REQUEST = 'POST_BOOK_REQUEST';
export const POST_BOOK_FAILURE = 'POST_BOOK_FAILURE';
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS';

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';

export const MULTIBOOK_WIDTH_CHANGE = 'MULTIBOOK_WIDTH_CHANGE';
export const MOUNT_MULTIBOOK = 'MOUNT_MULTIBOOK';

export const VIEW_SINGLE_BOOK = 'VIEW_SINGLE_BOOK';