const types = {}

export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const TYPING = 'TYPING';
export const CLEAR_TYPING = 'CLEAR_TYPING';
export const ADD_BOOK_QUERY = 'ADD_BOOK_QUERY';
export const INVALID_SOURCE = 'INVALID_SOURCE';

export const USER_CHANGES = 'USER_CHANGES';
export const UPDATE_INFO = 'UPDATE_INFO';

export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_NEW_BOOK_SUCCESS = 'GET_NEW_BOOK_SUCCESS';
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
export const GET_NEXT_BOOK = 'GET_NEXT_BOOK';

export const POST_BOOK_REQUEST = 'POST_BOOK_REQUEST';
export const POST_BOOK_FAILURE = 'POST_BOOK_FAILURE';
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS';

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';

export const MULTIBOOK_WIDTH_CHANGE = 'MULTIBOOK_WIDTH_CHANGE';
export const MOUNT_MULTIBOOK = 'MOUNT_MULTIBOOK';
export const NO_LOAD = 'NO_LOAD';
export const CHANGE_NAV_SELECTION = 'CHANGE_NAV_SELECTION';

export const GET_AVAILABLE_BOOKS_REQUEST = 'GET_AVAILABLE_BOOKS_REQUEST';
export const GET_AVAILABLE_BOOKS_SUCCESS = 'GET_AVAILABLE_BOOKS_SUCCESS';
export const GET_AVAILABLE_BOOKS_FAILURE = 'GET_AVAILABLE_BOOKS_FAILURE';
export const ADD_BOOKS = 'ADD_BOOKS';

export const VIEW_SINGLE_BOOK = 'VIEW_SINGLE_BOOK';
export const RESET_VIEW = 'RESET_VIEW';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const GET_ALL_TRADES_REQUEST = 'GET_ALL_TRADES_REQUEST';
export const GET_ALL_TRADES_FAILURE = 'GET_ALL_TRADES_FAILURE';
export const GET_ALL_TRADES_SUCCESS = 'GET_ALL_TRADES_SUCCESS';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const SELECT_REQUESTED_BOOK = 'SELECT_REQUESTED_BOOK';
export const SELECT_USER_BOOK = 'SELECT_USER_BOOK';
export const PROPOSE_TRADE_SUCCESS = 'PROPOSE_TRADE_SUCCESS'; 
export const PROPOSE_TRADE_REQUEST = 'PROPOSE_TRADE_REQUEST';
export const PROPOSE_TRADE_FAILURE = 'PROPOSE_TRADE_FAILURE';